version: '3.7'

services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app
    env_file:
      - .env
      
  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 7010:8000
    depends_on:
      - db
      - redis
    


