"""drop id

Revision ID: 9b7e37c8a47d
Revises: 072566cf619a
Create Date: 2024-06-12 12:24:58.803577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b7e37c8a47d"
down_revision: Union[str, None] = "072566cf619a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("shops_workers_id_fkey", "shops", type_="foreignkey")
    op.drop_column("shops", "workers_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shops",
        sa.Column(
            "workers_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "shops_workers_id_fkey", "shops", "persons", ["workers_id"], ["id"]
    )
    # ### end Alembic commands ###
