"""shop

Revision ID: 628febdeb1f1
Revises: 70cb330df104
Create Date: 2024-06-12 08:54:48.730670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "628febdeb1f1"
down_revision: Union[str, None] = "70cb330df104"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shops", "products", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shops", "products", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
