"""create tables

Revision ID: e9dd86f8b2bd
Revises: 628febdeb1f1
Create Date: 2024-06-12 09:35:02.007624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9dd86f8b2bd"
down_revision: Union[str, None] = "628febdeb1f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shops",
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("products", sa.String(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "persons",
        sa.Column("first_name", sa.String(length=10), nullable=False),
        sa.Column("second_name", sa.String(length=15), nullable=False),
        sa.Column("years", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.Column("email", sa.String(length=20), nullable=False),
        sa.Column("work_place_name", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_place_name"],
            ["shops.title"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persons")
    op.drop_table("shops")
    # ### end Alembic commands ###
