"""product table

Revision ID: d65135b83fd4
Revises: 9b7e37c8a47d
Create Date: 2024-06-12 13:48:53.266558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d65135b83fd4"
down_revision: Union[str, None] = "9b7e37c8a47d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column(
            "type",
            sa.Enum("technical", "food", "books", name="producttypes"),
            nullable=False,
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("shops", "products")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shops",
        sa.Column(
            "products", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_table("products")
    # ### end Alembic commands ###
