"""workers id

Revision ID: 072566cf619a
Revises: bbc3381730b4
Create Date: 2024-06-12 12:23:00.158778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "072566cf619a"
down_revision: Union[str, None] = "bbc3381730b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shops", sa.Column("workers_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "shops", "persons", ["workers_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shops", type_="foreignkey")
    op.drop_column("shops", "workers_id")
    # ### end Alembic commands ###
