"""refresh foreign key

Revision ID: 70cb330df104
Revises: 81854bd52aeb
Create Date: 2024-06-11 16:36:45.529927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70cb330df104"
down_revision: Union[str, None] = "81854bd52aeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persons",
        sa.Column("work_place_name", sa.String(length=20), nullable=True),
    )
    op.drop_constraint(
        "persons_work_place_id_fkey", "persons", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "persons", "shops", ["work_place_name"], ["title"]
    )
    op.drop_column("persons", "work_place_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persons",
        sa.Column(
            "work_place_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "persons", type_="foreignkey")
    op.create_foreign_key(
        "persons_work_place_id_fkey",
        "persons",
        "shops",
        ["work_place_id"],
        ["id"],
    )
    op.drop_column("persons", "work_place_name")
    # ### end Alembic commands ###
