"""unique products titles

Revision ID: 703c5d57f4f3
Revises: 6bde8f2cc815
Create Date: 2024-06-12 14:07:36.260917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "703c5d57f4f3"
down_revision: Union[str, None] = "6bde8f2cc815"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "products", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    # ### end Alembic commands ###
