"""unique email

Revision ID: bbc3381730b4
Revises: 8414cf9d6cfe
Create Date: 2024-06-12 11:57:58.059739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbc3381730b4"
down_revision: Union[str, None] = "8414cf9d6cfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "persons", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "persons", type_="unique")
    # ### end Alembic commands ###
