"""fix name of collumns assotiation table

Revision ID: 247205031c04
Revises: d2a3b05c28cc
Create Date: 2024-06-12 15:00:47.994762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "247205031c04"
down_revision: Union[str, None] = "d2a3b05c28cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shop_assotiation_table",
        sa.Column("product_title", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "shop_assotiation_table",
        sa.Column("shop_title", sa.String(length=20), nullable=False),
    )
    op.drop_constraint(
        "shop_assotiation_table_product_id_fkey",
        "shop_assotiation_table",
        type_="foreignkey",
    )
    op.drop_constraint(
        "shop_assotiation_table_shop_id_fkey",
        "shop_assotiation_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "shop_assotiation_table",
        "shops",
        ["shop_title"],
        ["title"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "shop_assotiation_table",
        "products",
        ["product_title"],
        ["title"],
        ondelete="CASCADE",
    )
    op.drop_column("shop_assotiation_table", "product_id")
    op.drop_column("shop_assotiation_table", "shop_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shop_assotiation_table",
        sa.Column(
            "shop_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "shop_assotiation_table",
        sa.Column(
            "product_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "shop_assotiation_table", type_="foreignkey")
    op.drop_constraint(None, "shop_assotiation_table", type_="foreignkey")
    op.create_foreign_key(
        "shop_assotiation_table_shop_id_fkey",
        "shop_assotiation_table",
        "shops",
        ["shop_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "shop_assotiation_table_product_id_fkey",
        "shop_assotiation_table",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("shop_assotiation_table", "shop_title")
    op.drop_column("shop_assotiation_table", "product_title")
    # ### end Alembic commands ###
