""">

Revision ID: bb3948b9ddcd
Revises: 68050a380aaf
Create Date: 2024-06-17 16:06:45.998165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb3948b9ddcd"
down_revision: Union[str, None] = "68050a380aaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages", "message", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages", "message", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
