"""fix id assotiation table

Revision ID: f98c88a9aaa3
Revises: 703c5d57f4f3
Create Date: 2024-06-12 14:57:39.135949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f98c88a9aaa3"
down_revision: Union[str, None] = "703c5d57f4f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopsassotiationtables",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "shop_id"),
    )
    op.drop_table("shop_assotiation_table")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_assotiation_table",
        sa.Column(
            "product_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "shop_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name="shop_assotiation_table_product_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name="shop_assotiation_table_shop_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "product_id", "shop_id", "id", name="shop_assotiation_table_pkey"
        ),
    )
    op.drop_table("shopsassotiationtables")
    # ### end Alembic commands ###
