"""shop

Revision ID: 81854bd52aeb
Revises: d7def9e6d15a
Create Date: 2024-06-11 15:42:31.642164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81854bd52aeb"
down_revision: Union[str, None] = "d7def9e6d15a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shops",
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("products", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.add_column(
        "persons", sa.Column("work_place_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "persons", "shops", ["work_place_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "persons", type_="foreignkey")
    op.drop_column("persons", "work_place_id")
    op.drop_table("shops")
    # ### end Alembic commands ###
